### ISSUE TITLE
YCSB-TEST

### ISSUE THREAD

**Issue by suxiao111** [hpides/viper#14]
I have an error generating a test dataset for ycsb, using ycsb-0.17 to generate the data, but after converting the data using the convert_ycsb.py script under the project, the data file becomes an empty file

**Comment by lawben** [comment]
Could you please give me some more details? Maybe the regex does not match the output of your generated ycsb files. Could you add a few lines here from the generated output?

**Comment by suxiao111** [comment]
I have solved it, and now I have encountered a new problem. When I enable ALL_BMS (RocksDbFixture) in ycsb_bm.cpp to compile PM-RocksDB, it always reports an error: 
invalid use of incomplete type ‘class RocksDbFixture_9010_zipf_lat_Benchmark’

**Comment by lawben** [comment]
Getting PmemRocksDb to run is a bit painful, so I have [disabled it in CMake](https://github.com/hpides/viper/blob/master/benchmark/CMakeLists.txt#L202-L204) for now. You need to re-add those lines and see if you can get that rocksdb version to run on your server. It is quite old and unmaintained, so it might be a bit tricky.
