### ISSUE TITLE
Where is the RESULT_JSON file ?

### ISSUE THREAD

**Issue by EasyLuck** [hpides/viper#17]
Hi,
I can not find the result_json file in your project files. Can you share this?
RESULT_JSON = "/Users/law/repos/viper/results/var_size/var_size_revision.json"
RESULT_JSON = "/Users/law/repos/viper/results/update/update_bm_revision.json"
and so on in the eval/xxx.ipynb

**Comment by lawben** [comment]
This archive should contain all files [results_vldb21.zip](https://github.com/hpides/viper/files/8873116/results_vldb21.zip). Note that this is a dump of the result files from the server. They might not be the correct ones. If something does not match up, please let me know.
