### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by zjs1224522500** [hpides/viper#5]
First of all, thank you for sharing your great works!

I tried to learn the src code to enhance my comprehension of Viper. And I have some questions when I read the src code.

  1. When calculate num_slots, as function `get_num_slots_per_page`, why need to plus 1? 
   ```C++
   const uint16_t page_overhead = sizeof(version_lock_t) + 1;
   ```
  2. Also in function `get_num_slots_per_page`, the condition `num_slots_per_page_large > 255`  is satisfied when the size of entry is less than 16Bytes, so there is an assumption that the smallest entry is 16Bytes, right? why to `num_slots_per_page_large--`? I guess to reserve metadata space. However, in the following code, there is a check for `num_slots_per_page`, so it seems like that the logic is duplicated. I'm not sure if there are any cases else I haven't considered.
   ```C++
    uint16_t num_slots_per_page_large = current_page_size / entry_size;
    if (num_slots_per_page_large > 255) {
        num_slots_per_page_large--;
    }
    data_offset_size_t num_slots_per_page = num_slots_per_page_large;
    while ((num_slots_per_page * entry_size) + page_overhead +
                std::ceil((double) num_slots_per_page / 8) > current_page_size) {
        num_slots_per_page--;
    }
   ```

Thx & BR

**Comment by lawben** [comment]
In general, the `get_num_slots_per_page` got a bit messy over time as I tried to do different things with it that changed a bit organically. 

1. The `+1` is needed, as a VPage as at least 1 Byte for the bitset. Even if there is only one entry, C++ requires 1 Byte for this. So I'm checking that a VPage has 1 Byte lock + (at least) 1 Byte bitset.

2. You are correct in the assumption that the minimum entry size is 16 Byte. The main reason for _**was**_ that we can only have 256 bits in the bitset, i.e., 8 Byte, as we need to update the bitset atomically. This requirement changed over time but the assumption stayed. You could probably change this with a few lines if you need it. Or for 4 Byte entries, you could simply cast them to 8 Byte values (e.g., uint64_t) or pad them.

The logic around `num_slots_per_page--` is indeed duplicated. Thanks for pointing this out. I believe the first check could be removed without any difference. I think I needed it for a different check a while back.
