### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by jiawen11** [hpides/viper#6]
Hi Lawrence, 

Thanks for your paper and the open-source code! When I compiled your code, I got the following error:

```
/home/test/viper/benchmark/fixtures/crl.hpp:25:48: error: ‘tbb::detail’ has not been declared
   25 |     static const size_t hash_multiplier = tbb::detail::select_size_t_constant<2654435769U, 11400714819323198485ULL>::value;
      |                                                ^~~~~~
/home/test/viper/benchmark/fixtures/crl.hpp:25:92: error: expected unqualified-id before numeric constant
   25 |     static const size_t hash_multiplier = tbb::detail::select_size_t_constant<2654435769U, 11400714819323198485ULL>::value;
```

I've installed all dependencies as shown in https://github.com/hpides/viper/blob/master/CMakeLists.txt. I look forward to your response. 

Thanks!

**Comment by lawben** [comment]
It looks like you forgot to install some dependencies listed in the [benchmark/CMakeLists.txt](https://github.com/hpides/viper/blob/master/benchmark/CMakeLists.txt), in this case TBB. 

Please also check out this issue #4 regarding building the benchmark stuff. I'd be happy to try and help you with the process and clean up the code-mess on my side. Unfortunately, various dependencies have different requirements which makes everything a bit tricky. 

Could you maybe share how you are building Viper? Are you cloning it and running `cmake ..` directly from the command line, via an IDE, or as a CMake-subproject?
