### ISSUE TITLE
Why `sfence` is not used in the code ?

### ISSUE THREAD

**Issue by Gooong** [hpides/viper#9]
Hi, 

Thanks for your great work. It's really inspiring. I have one question: In the Viper code there is no `sfence` function called explicitly. However, as the paper mentions:

> To write the current cache line to PMem, the Persist method issues a clwb call to the underlying system followed by an sfence call.

Why `sfence` is not used in the code ?

**Comment by lawben** [comment]
Thanks for catching this! I introduced this bug in a recent commit ([8947986](https://github.com/hpides/viper/commit/8947986f1996b66c2d4d3e9bfdc0ba4d3c88abb2)) that removed PMDK. I'll update the code immediately.

**Comment by lawben** [comment]
Added in [e04d307](https://github.com/hpides/viper/commit/e04d3079ac960b5e36f4fc8e5e8d8b42cb26aa86). Thanks again for pointing this out.
